# Generated by Django 3.2.17 on 2023-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='album',
            field=models.CharField(max_length=100, null=True, verbose_name='アルバム名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', '女性'), ('2', '男性')], max_length=1, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='曲名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearly_income',
            field=models.IntegerField(null=True, verbose_name='年収(万円)'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
