# Generated by Django 3.2.17 on 2023-02-13 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearly_income',
        ),
        migrations.AddField(
            model_name='profile',
            name='acousticness',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 26, 13, 190676, tzinfo=utc), verbose_name='アコースティック度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='album',
            field=models.CharField(default=datetime.datetime(2023, 2, 13, 11, 26, 45, 230063, tzinfo=utc), max_length=100, verbose_name='アルバム名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='artist',
            field=models.CharField(default=datetime.datetime(2023, 2, 13, 11, 26, 52, 377064, tzinfo=utc), max_length=100, verbose_name='アーティスト名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='danceability',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 26, 56, 931664, tzinfo=utc), verbose_name='ダンス度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='energy',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 1, 697653, tzinfo=utc), verbose_name='エネルギー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='instrumentalness',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 4, 852800, tzinfo=utc), verbose_name='インスト感'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='length',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 8, 794632, tzinfo=utc), verbose_name='曲の長さ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='liveness',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 16, 945998, tzinfo=utc), verbose_name='ライブさ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='loudness',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 22, 197958, tzinfo=utc), verbose_name='音の大きさ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 26, 451107, tzinfo=utc), verbose_name='曲調(1:メジャー,2:マイナー)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='popularity',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 28, 982485, tzinfo=utc), verbose_name='人気度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 27, 32, 545404, tzinfo=utc), verbose_name='リリース日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='speechiness',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 35, 67111, tzinfo=utc), verbose_name='スピーチ度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tempo',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 37, 699432, tzinfo=utc), verbose_name='曲のテンポ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='time_signature',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 39, 807618, tzinfo=utc), verbose_name='拍子'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='valence',
            field=models.IntegerField(default=datetime.datetime(2023, 2, 13, 11, 27, 41, 809688, tzinfo=utc), verbose_name='曲のポジティブ度'),
            preserve_default=False,
        ),
    ]
