# Generated by Django 3.2.17 on 2023-02-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20230213_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='artist',
            field=models.CharField(max_length=100, null=True, verbose_name='アーティスト名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='length',
            field=models.IntegerField(null=True, verbose_name='曲の長さ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.CharField(choices=[('1', 'メジャー'), ('2', 'マイナー')], max_length=1, null=True, verbose_name='曲調'),
        ),
    ]
