# Generated by Django 3.2.17 on 2023-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20230214_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearly_income',
        ),
        migrations.AddField(
            model_name='profile',
            name='acousticness',
            field=models.FloatField(null=True, verbose_name='アコースティック度'),
        ),
        migrations.AddField(
            model_name='profile',
            name='danceability',
            field=models.FloatField(null=True, verbose_name='ダンス度'),
        ),
        migrations.AddField(
            model_name='profile',
            name='popularity',
            field=models.IntegerField(null=True, verbose_name='人気度'),
        ),
    ]
